version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - redis
    command: "pipenv run flask --app app.web run --host=0.0.0.0 --port=5000"

  worker:
    build: .
    depends_on:
      - redis
    command: "pipenv run inv devworker"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"