version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    command: "pipenv run flask --app app.web run --host=0.0.0.0 --port=5000"

  worker:
    build: .
    command: "pipenv run inv prodworker"
